name: Deploy Backend to Render

on:
  push:
    branches: [main]
    paths:
      - "Rise.Server/**"
      - "Rise.Services/**"
      - "Rise.Domain/**"
      - "Rise.Persistence/**"
      - "Rise.Shared/**"
      - "render.yaml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install TailwindCSS dependencies
        working-directory: ./Rise.Client
        run: npm install

      - name: Build TailwindCSS
        working-directory: ./Rise.Client
        run: npm run build:css

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c Release

      - name: Test
        run: dotnet test --no-build -c Release --verbosity normal

      - name: Deploy to Render
        uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: ${{ secrets.RENDER_SERVICE_ID }}
          api_key: ${{ secrets.RENDER_API_KEY }}
          clear_cache: false
