name: Deploy Frontend to Vercel

on:
  push:
    branches: [main]
    paths:
      - "Rise.Client/**"
      - "Rise.Shared/**"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install TailwindCSS dependencies
        working-directory: ./Rise.Client
        run: npm install

      - name: Build TailwindCSS
        working-directory: ./Rise.Client
        run: npm run build:css

      - name: Restore .NET dependencies
        run: dotnet restore

      - name: Publish Blazor WebAssembly
        run: dotnet publish Rise.Client/Rise.Client.csproj -c Release -o ./wwwroot

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          working-directory: ./wwwroot/wwwroot
